- type: accessGroup
  id: meta
  tags:
  - EmergencyShuttleRepealAll
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - merc
  - Lawyer
  - Engineering
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
